[mypy]
# Ignore missing imports for third-party libraries without type stubs
ignore_missing_imports = True
disable_error_code = var-annotated, has-type, attr-defined, method-assign, assignment, arg-type, union-attr, typeddict-item

# Enable strict checking configuration
check_untyped_defs = True
warn_unused_ignores = True
warn_redundant_casts = True
