"""Feedback and prompt adjustment builder for answer regeneration retries."""

from core.logger import logger


def get_retry_feedback(
    question: str,
    previous_answer: str,
    verification_reason: str,
) -> str:
    """Generates a feedback prompt instruction targeting the previous response failure.

    Args:
        question: The user query.
        previous_answer: The failed answer text generated by the LLM.
        verification_reason: Explanation of the verification failure.

    Returns:
        str: Instructions to be appended to the next prompt execution.
    """
    logger.info("Verifier: Building self-correction feedback for LLM retry...")

    feedback = (
        f"CRITICAL FEEDBACK FOR CORRECTION:\n"
        f"Your previous answer attempt was flagged as invalid or ungrounded.\n"
        f"Failed Answer Attempt:\n\"{previous_answer}\"\n\n"
        f"Reason for Failure:\n\"{verification_reason}\"\n\n"
        f"Task:\n"
        f"Please rewrite your answer to the user question: \"{question}\".\n"
        f"Follow these rules strictly:\n"
        f"1. Remove all ungrounded assumptions, figures, or claims not explicitly found in the context documents.\n"
        f"2. Only list citations for documents actually present in the context. Do not invent document names.\n"
        f"3. Make sure to return your answer strictly formatted in the requested JSON structure."
    )
    return feedback
