"""JSON extractor and parser utility for raw LLM text outputs."""

import json
import re
from typing import Any, Dict
from core.logger import logger


def parse_json_response(raw_text: str) -> Dict[str, Any]:
    """Cleans and decodes JSON objects from raw text payloads.

    Supports stripping markdown ```json codes and isolating braces.

    Args:
        raw_text: Text generated by the LLM.

    Returns:
        Dict[str, Any]: The loaded dictionary object.

    Raises:
        ValueError: If JSON loading fails.
    """
    logger.info("Attempting to parse JSON block from raw LLM output...")
    cleaned = raw_text.strip()

    # 1. Search for markdown code block wraps: ```json ... ```
    match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", cleaned, re.DOTALL | re.IGNORECASE)
    if match:
        cleaned = match.group(1)
    else:
        # 2. Isolate text between the first '{' and last '}'
        start = cleaned.find("{")
        end = cleaned.rfind("}")
        if start != -1 and end != -1:
            cleaned = cleaned[start : end + 1]

    try:
        decoded = json.loads(cleaned)
        logger.info("Successfully extracted and loaded JSON response.")
        return decoded
    except json.JSONDecodeError as e:
        logger.error(f"JSON decode failed. Raw payload:\n{raw_text}\nError: {e}")
        raise ValueError(f"Model output did not contain valid JSON syntax: {e}")
